[profile.default]
src = "contracts"
out = "artifacts"
libs = ["lib", "node_modules"]
remappings = [
  "@ensdomains/=node_modules/@ensdomains/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@uniswap/=node_modules/@uniswap/",
  "base64-sol/=node_modules/base64-sol/",
  "forge-std/=lib/forge-std/src/",
  "hardhat/=node_modules/hardhat/",
]

fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
